{% set version = "0.3.21" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-littler
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/littler_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/littler/littler_{{ version }}.tar.gz
  sha256: 9e8be7aca97ef31ecc7af845954caddf52f9dad4d28ee1392dca829b75e64085

build:
  number: 0
  skip: true  # [not unix]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - zlib
  run:
    - r-base

test:
  commands:
    - $R -e "library('littler')"           # [not win]
    - r --version                          # [linux]
    - lr --version                         # [osx]
    - "\"%R%\" -e \"library('littler')\""  # [win]

about:
  home: https://dirk.eddelbuettel.com/code/littler.html
  dev_url: https://github.com/eddelbuettel/littler
  license: GPL-2.0-or-later
  summary: A scripting and command-line front-end is provided by 'r' (aka 'littler') as a lightweight binary wrapper around the GNU R language and environment for statistical computing and graphics. While R can be used in batch mode, the r binary adds full support for both 'shebang'-style scripting (i.e. using a  hash-mark-exclamation-path
    expression as the first line in scripts) as well as command-line use in standard Unix pipelines. In other words, r provides the R language without the environment.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
