travis:
  secure:
    BINSTAR_TOKEN: FRqhd2tEryymyD+6Tr6UjyaErrd5wiuQxvHtuj7L+ZiGD/A1YuLVqzfiD02FdbKGbP6waKL1ZOTT4OdUzqzgWez4ORzpaSTOQ7jtiaQ/CFIsbkfpXuyzhGZ4U2Fw991vVk3psj6U3PF8K5AebMhWzS5gIuB7OUs0Br3Dm3nUI9wmfcL7/h/tmHGaWXkcLgb+YHLbxTOctBh+DPSfa6SI5NDT1F8wIj6LIt+MsSI7L8e6g74C3q8Y0o9hTgWKbJDAJSdnCxqWtjmxxx5jAzJInnv0hLfYc44P+QAf2mqDdmLhYU7UBOb6ot4KZ18gMESYdjg2TuFQL4xHKeaZ6mjrOUKh0ZUpysYj7J9cDitwPHAFHOLmn5Xn4dv4IdS6EpjVuCNUIvZJFFrfW8TuUYnr1npGdh03wsF9gIGM+0BQf74IB9O0OOBxEepARSKURSqCGz3TDdnNhmOuyjbywWci2U57QYZAfiUxCdacYYyfx7p3X8LbKZud2AvdKK419XKEEP0KWd8K5q5VfRJuAx6b73bf7lKhhpfegXmiAt0aoRqHTRauixw+wi3OF46iqKG5vXna/KzfTVkNdl5y1m3VNS176okZJKN+xhmpMXKrzyLMSIHtoWkFLcjSG/wEzNO+uChooEsGdPH+vcZ3gRolGmlead0iofLbrXm/3phYGzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
